NDefines.NDiplomacy.EMPEROR_REVOKE_AUTHORITY_COST = 75.0
NDefines.NDiplomacy.HRE_FOREIGN_CONTROL_PENALTY = -0.02
NDefines.NDiplomacy.HRE_PRINCE_AUTHORITY_THRESHOLD = 20
NDefines.NDiplomacy.IMPERIAL_AUTHORITY_FROM_PRINCES = 0.1
NDefines.NDiplomacy.JOIN_HRE_DEVELOPMENT_CAP_VASSAL = 400
NDefines.NDiplomacy.LACK_OF_ELECTORS_HIT = -0.3
NDefines.NDiplomacy.MAX_FREE_CITIES = 15
