NDiplomacy = {
  MAX_FREE_CITIES = 15,
  HRE_PRINCE_AUTHORITY_THRESHOLD = 20,
  IMPERIAL_AUTHORITY_FROM_PRINCES = 0.085,
  HRE_FOREIGN_CONTROL_PENALTY = -0.01,
  LACK_OF_ELECTORS_HIT = -0.15,
  JOIN_HRE_DEVELOPMENT_CAP_VASSAL = 400,
  EMPEROR_REVOKE_AUTHORITY_COST = 75.0,
}