NDefines.NCountry.DEBT_LIMIT_DIP = -100

NDefines.NDiplomacy.EMPEROR_REVOKE_AUTHORITY_COST = 75.0
NDefines.NDiplomacy.HRE_FOREIGN_CONTROL_PENALTY = -0.04
NDefines.NDiplomacy.HRE_PRINCE_AUTHORITY_THRESHOLD = 30
NDefines.NDiplomacy.IMPERIAL_AUTHORITY_FROM_PRINCES = 0.125
NDefines.NDiplomacy.JOIN_HRE_DEVELOPMENT_CAP_VASSAL = 400
NDefines.NDiplomacy.LACK_OF_ELECTORS_HIT = -0.75
NDefines.NDiplomacy.MAX_FREE_CITIES = 15
NDefines.NDiplomacy.IMPERIAL_REFORM_AUTHORITY_ACCEPTANCE = 2

NDefines.NMilitary.SUPPLYLIMIT_BASE_MULTIPLIER = 16
